name: Build and test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Install the project
        run: uv sync --locked --dev # --all-extras

      - name: Check code format (ruff)
        run: uv run ruff format --check .

      - name: Check code format (tombi)
        run: uv run tombi format --check

      - name: Lint code (ruff)
        run: uv run ruff check .

      - name: Lint code (tombi)
        run: uv run tombi lint

      - name: Type check (mypy)
        run: uv run mypy .

      - name: Run tests (pytest)
        run: uv run coverage run -m pytest .

      - name: Build package
        if: ${{ matrix.python-version == '3.13' }} # build only on latest supported Python
        run: |
          export SOURCE_DATE_EPOCH=$(date +%s)
          echo "SOURCE_DATE_EPOCH: $SOURCE_DATE_EPOCH"
          uv build

      - name: Upload package distributions to GitHub
        if: ${{ matrix.python-version == '3.13' }} # upload only on latest supported Python
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package
          path: dist/
          if-no-files-found: error
