on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: pip

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install '.[dev]'

      - run: |
          export SOURCE_DATE_EPOCH=$(date +%s)
          echo "SOURCE_DATE_EPOCH: $SOURCE_DATE_EPOCH"
          python -m build

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # TODO: https://github.com/cj81499/json_types/issues/3
      - name: Install package
        run: python -m pip install '.[dev]'

      - name: Check code format (black)
        run: python -m black --check .

      - name: Lint code (ruff)
        run: python -m ruff check .

      - name: Type check (mypy)
        run: python -m mypy .

      - name: Run tests (pytest)
        run: python -m coverage run -m pytest .

  # TODO: https://github.com/cj81499/json_types/issues/2
  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
