name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml

  collector:
    needs: [build-and-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo Job failed
          exit 1
