name: Release

on:
  # for now, releases will be manually triggered
  # it'd be nice to
  workflow_dispatch:
    inputs:
      publish-to:
        type: choice
        description: The URL of the PyPI repository to publish to
        required: true
        options:
          - https://test.pypi.org/legacy/ # for testing
          - https://upload.pypi.org/legacy/ # for release

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml

  publish:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package
          path: dist/

        # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.publish-to }}
