on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: pip

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install '.[build]'

      - name: Build package
        run: |
          export SOURCE_DATE_EPOCH=$(date +%s)
          echo "SOURCE_DATE_EPOCH: $SOURCE_DATE_EPOCH"
          python -m build

      - name: Upload package distributions to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Download package distributions from GitHub
        uses: actions/download-artifact@v3
        id: download-package
        with:
          name: package
          path: dist/

      - name: Install tools and package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          export WHEEL_PATH=$(find ./dist -type f -name '*.whl')
          python -m pip install "$WHEEL_PATH"\[dev\]

      - name: Check code format (black)
        run: python -m black --check .

      - name: Lint code (ruff)
        run: python -m ruff check .

      - name: Type check (mypy)
        run: python -m mypy .

      - name: Run tests (pytest)
        run: python -m coverage run -m pytest .
